# lang.py

# English Translations
EN = {
    "sample_text_label": "Choose a Sample Text Genre:",
    "app_title": "QuantumLeap AI: A Conceptual Demo",
    "app_intro": "This project demonstrates the idea of a **Quantum Leap** in technology. We will analyze the same text using two methods:",
    "old_state_title": "Old State:",
    "old_state_desc": "A simple, rule-based system.",
    "quantum_leap_title": "Quantum Leap:",
    "quantum_leap_desc": "A modern, AI-powered system using state-of-the-art models.",
    "text_input_label": "Enter some text to analyze:",
    "analyze_button": "Analyze with a Quantum Leap!",
    "warning_no_text": "Please enter some text to analyze.",
    "advanced_analysis_header": "🔬 Advanced Analysis",
    "keyword_extraction_header": "Keyword Extraction",
    "keyword_extraction_desc": "Let's see how each system identifies the most important topics in the text.",
    "extract_keywords_button": "Extract Keywords",
    "qa_header": "Question Answering",
    "qa_desc": "Now, ask a question about the text and see who can answer it better.",
    "qa_input_label": "Ask a question about the text above:",
    "ask_question_button": "Ask Question",
    "warning_no_text_or_question": "Please enter both text and a question.",
    "about_title": "About QuantumLeap AI",
    "about_intro": "Welcome to the QuantumLeap AI project. This application is a conceptual demonstration of the dramatic difference between traditional programming and modern artificial intelligence.",
    "about_mission_header": "Our Mission",
    "about_mission_text": "To make the abstract concept of a 'quantum leap' in technology tangible and understandable. By comparing a simple, rule-based system with a powerful AI model side-by-side, we aim to showcase the incredible advancements in natural language processing.",
    "about_tech_header": "Technology Used",
    "about_tech_text": "This project is built with Python and the Streamlit library. The 'Quantum Leap' is powered by state-of-the-art transformer models from Hugging Face, including models for sentiment analysis, summarization, question answering, and keyword extraction.",
    "about_contribute_header": "Contribute",
    "about_contribute_text": "This is an open-source educational project. If you have ideas for new features or improvements, feel free to contribute!",
    "ner_header": "Named Entity Recognition",
    "ner_desc": "Let's see if the AI can identify People, Organizations, and Locations.",
    "extract_entities_button": "Extract Entities",
    "people_label": "👤 People",
    "orgs_label": "🏢 Organizations",
    "locs_label": "📍 Locations",
    "misc_label": "🗂️ Miscellaneous",
}

# Bangla Translations
BN = {
    "sample_text_label": "একটি নমুনা টেক্সট ধরন নির্বাচন করুন:",
    "app_title": "কোয়ান্টামলিপ AI: একটি ধারণাগত ডেমো",
    "app_intro": "এই প্রকল্পটি প্রযুক্তিতে একটি **'কোয়ান্টাম লিপ'** এর ধারণাটি প্রদর্শন করে। আমরা দুটি পদ্ধতি ব্যবহার করে একই টেক্সট বিশ্লেষণ করব:",
    "old_state_title": "পুরনো অবস্থা:",
    "old_state_desc": "একটি সাধারণ, নিয়ম-ভিত্তিক সিস্টেম।",
    "quantum_leap_title": "কোয়ান্টাম লিপ:",
    "quantum_leap_desc": "আধুনিক, AI-চালিত সিস্টেম যা সর্বশেষ মডেল ব্যবহার করে।",
    "text_input_label": "বিশ্লেষণের জন্য কিছু টেক্সট লিখুন:",
    "analyze_button": "একটি কোয়ান্টাম লিপ দিয়ে বিশ্লেষণ করুন!",
    "warning_no_text": "অনুগ্রহ করে বিশ্লেষণের জন্য কিছু টেক্সট লিখুন।",
    "advanced_analysis_header": "🔬 উন্নত বিশ্লেষণ",
    "keyword_extraction_header": "কীওয়ার্ড এক্সট্র্যাকশন",
    "keyword_extraction_desc": "আসুন দেখি প্রতিটি সিস্টেম টেক্সটের সবচেয়ে গুরুত্বপূর্ণ বিষয়গুলি কীভাবে সনাক্ত করে।",
    "extract_keywords_button": "কীওয়ার্ড বের করুন",
    "qa_header": "প্রশ্নোত্তর",
    "qa_desc": "এখন, টেক্সট সম্পর্কে একটি প্রশ্ন জিজ্ঞাসা করুন এবং কে এটি আরও ভালোভাবে উত্তর দিতে পারে তা দেখুন।",
    "qa_input_label": "উপরের টেক্সট সম্পর্কে একটি প্রশ্ন জিজ্ঞাসা করুন:",
    "ask_question_button": "প্রশ্ন জিজ্ঞাসা করুন",
    "warning_no_text_or_question": "অনুগ্রহ করে টেক্সট এবং প্রশ্ন উভয়ই লিখুন।",
    "about_title": "কোয়ান্টামলিপ AI সম্পর্কে",
    "about_intro": "কোয়ান্টামলিপ AI প্রকল্পে আপনাকে স্বাগতম। এই অ্যাপ্লিকেশনটি ঐতিহ্যবাহী প্রোগ্রামিং এবং আধুনিক কৃত্রিম বুদ্ধিমত্তার মধ্যে নাটকীয় পার্থক্যের একটি ধারণাগত প্রদর্শনী।",
    "about_mission_header": "আমাদের লক্ষ্য",
    "about_mission_text": "প্রযুক্তিতে একটি 'কোয়ান্টাম লিপ'-এর বিমূর্ত ধারণাটিকে স্পর্শকাতর এবং বোধগম্য করে তোলা। একটি সাধারণ, নিয়ম-ভিত্তিক সিস্টেমকে একটি শক্তিশালী AI মডেলের পাশাপাশি তুলনা করে, আমরা প্রাকৃতিক ভাষা প্রক্রিয়াকরণে অবিশ্বাস্য অগ্রগতি প্রদর্শন করতে চাই।",
    "about_tech_header": "ব্যবহৃত প্রযুক্তি",
    "about_tech_text": "এই প্রকল্পটি Python এবং Streamlit লাইব্রেরি দিয়ে তৈরি। 'কোয়ান্টাম লিপ'-টি Hugging Face-এর সর্বশেষ ট্রান্সফরমার মডেল দ্বারা চালিত হয়, যার মধ্যে সেন্টিমেন্ট বিশ্লেষণ, সারসংক্ষেপ, প্রশ্নোত্তর এবং কীওয়ার্ড এক্সট্র্যাকশনের মডেল রয়েছে।",
    "about_contribute_header": "অবদান রাখুন",
    "about_contribute_text": "এটি একটি ওপেন-সোর্স শিক্ষামূলক প্রকল্প। আপনার যদি নতুন বৈশিষ্ট্য বা উন্নতির ধারণা থাকে, তবে অবদান রাখতে নির্দ্বিধায়!",
    "ner_header": "নামযুক্ত সত্তা শনাক্তকরণ",
    "ner_desc": "আসুন দেখি AI মানুষ, প্রতিষ্ঠান এবং স্থান সনাক্ত করতে পারে কিনা।",
    "extract_entities_button": "সত্তা বের করুন",
    "people_label": "👤 ব্যক্তিবর্গ",
    "orgs_label": "🏢 প্রতিষ্ঠান",
    "locs_label": "📍 স্থান",
    "misc_label": "🗂️ বিবিধ",
}