# sample_texts.py

# A dictionary to hold all our sample texts.
# The key will be the display name, and the value will be the long paragraph.
SAMPLE_TEXTS = {
    "Essay (Technology & Society)": """
    The relentless march of technological progress has long been celebrated as the primary engine of human prosperity and enlightenment. From the invention of the printing press, which democratized knowledge, to the development of the internet, which connected the globe in an unprecedented web of information, each leap forward has been hailed as a step towards a better, more efficient, and more equitable world. We are told that automation will free us from toil, that artificial intelligence will solve our most complex problems, and that biotechnology will cure our most intractable diseases. This narrative of technological salvation is powerful and seductive, promising a future where scarcity is abolished and human potential is fully realized. Yet, this optimistic view often overlooks the profound and frequently disruptive dual nature of progress. For every problem solved, a new one seems to emerge, often more complex and insidious than the last. The industrial revolution, while generating immense wealth, also led to the squalor of the urban poor and the degradation of the natural environment. The internet, a tool for connection and learning, has also become a vector for misinformation, social polarization, and the erosion of privacy. The very technologies that promise to liberate us can also become the most subtle and effective instruments of control. The challenge of our time is not to halt progress, for that is both impossible and undesirable. Rather, it is to steer its trajectory with wisdom, foresight, and a deep commitment to humanistic values. We must ask not only "Can we build it?" but also "Should we build it?" and "Who will it benefit?" We must foster a public discourse that is sophisticated enough to understand the trade-offs inherent in any new technology, and we must develop regulatory frameworks that are agile enough to keep pace with rapid innovation without stifling it. The future is not something that merely happens to us; it is something we actively build. The tools we have are more powerful than ever, and so too is our responsibility to wield them with care, ensuring that the quantum leaps of our generation lead not to a fragmented dystopia, but to a more just, sustainable, and humane world for generations to come.
    """,

    "Drama (Monologue)": """
    You look at this crown, this heavy circle of cold gold, and you see power. You see glory. You see the answer to every prayer you ever whispered in the dark. I see a cage. I see a weight that has crushed the man I used to be. Do you remember him? The boy who would rather get lost in the woods than sit through a lesson? The young man who fell in love with a stable girl's laugh and thought that was the only treasure he'd ever need? I don't. I have to search for his face in old portraits, and even then, his eyes seem to belong to a stranger. They say a king is two men: the man he is, and the man he must be. I have been two men for so long, I have forgotten which one is the ghost. The man I must be is decisive, ruthless, and above all, certain. He never doubts. He never questions. He signs the decree that sends a thousand men to their deaths and then sleeps soundly. He marries for alliance, not for love, and tells himself it is a small sacrifice for the stability of the realm. I have made all the right decisions. I have strengthened the borders, filled the treasury, and silenced my enemies. The kingdom is secure. And I have never been more alone. This court is a nest of vipers, smiling and bowing while they plot my downfall. Every friend is a potential traitor, every compliment a veiled threat. The only moments of peace I find are in the silence of the armory, holding a sword. It is an honest thing. It has one purpose. It does not lie. It does not flatter. But I cannot rule a kingdom with a sword. I must rule with words, with decrees, with a smile that I no longer feel. They brought me this crown, polished and gleaming, and placed it on my head. They called it an honor. They did not tell me it would be a shroud. They did not tell me it would bury the boy I was, alive. So do not wish for my life. Do not envy the man who sits on this throne. Envy the boy in the woods, the lover in the field. They are the ones who were truly free.
    """,

    "Story (Fantasy)": """
    The Whisperwood did not suffer fools, and Kaelen was beginning to fear he was one of them. He had been tracking the Moonpetal Stag for three days, a creature of legend said to grant a single, perfect wish to whoever could capture its silver antlers. Now, deep in the heart of the ancient forest, the air itself seemed to work against him. The path he had followed had vanished, swallowed by a carpet of glowing moss that pulsed with a soft, internal light. The trees, ancient and colossal with bark like polished obsidian, seemed to shift their positions when he wasn't looking, their branches weaving together to block out the sky. He was utterly, hopelessly lost. A sound, like the chiming of a thousand tiny bells, drew him forward. He pushed through a curtain of hanging vines and stepped into a clearing. In the center stood a pool of water, so still and black it looked like a hole cut out of the world. And there, drinking from the pool, was the Stag. It was more magnificent than any story had described. Its coat was the color of starlight, its hooves were polished silver, and its antlers were not bone but pure, solid moonlight, casting a gentle, silvery glow on the surroundings. Kaelen froze, his heart hammering against his ribs. His hand went to the iron net on his back, the tool he had crafted for this very moment. But he hesitated. The Stag raised its head, its eyes like pools of liquid wisdom, and looked directly at him. It did not startle or run. It simply watched him. In that gaze, Kaelen saw not an animal to be captured, but a guardian, a spirit of this sacred place. He thought of the wish he had planned to make: to bring his sister back from the dead. It was a selfish wish, a wish born of grief and desperation. He saw now that it would be a violation, a tearing of the natural order. The Stag took a step towards him, its chime growing softer, more intimate. It lowered its head, not in submission, but in offering. Kaelen understood. He slowly, deliberately, unslung the iron net from his back and let it fall to the mossy ground. He had come to take something from the Whisperwood, but now he saw that the only thing he could take was the memory of its beauty. He bowed his head, and when he looked up again, the Stag was gone. The pool was just a pool, and the clearing was empty. But on the ground where the Stag had stood, a single, perfect Moonpetal lay glowing, a gift not of a granted wish, but of a lesson learned.
    """,

    "Science Fiction": """
    The signal was a ghost, a whisper from a dead star. For seventy years, it had been traveling across the void, a faint, complex radio burst that the deep space observatory on Phobos had finally isolated. Dr. Aris Thorne had spent the last six months of his life decoding it, his life's work culminating in a string of data that was not a message, but a blueprint. It was the schematic for a machine of incomprehensible design, a device that manipulated quantum foam to generate stable, traversable wormholes. Humanity had been given the key to the stars, but the door it opened led to a place of terrifying silence. The first probe sent through the wormhole arrived in orbit around a planet orbiting the star Proxima Centauri. It was a world much like Earth, with blue oceans and swirling white clouds. But it was utterly silent. No radio signals, no signs of industry, no heat signatures from cities. Scans revealed sprawling, abandoned cities of geometric perfection, overgrown with alien vegetation. There were no bodies, no signs of war or plague. It was as if the entire population, a civilization that had clearly mastered the cosmos, had simply vanished. Thorne, now leading the first manned mission through the gateway, stood on the bridge of the starship *Odyssey*, watching the silent planet grow on the main viewscreen. "What could do that?" asked Commander Eva Rostova, her voice tight with a tension they all felt. "A technology so advanced it became indistinguishable from magic," Thorne replied, his eyes glued to the data streaming from the probes. "Or a problem so profound that even a god-like civilization couldn't solve it." They found the answer in the central data spire of the largest city. It was a final log, a universal message left by the beings who called themselves the Architects. They had achieved everything. They had conquered disease, death, and the laws of physics itself. They had uploaded their consciousness into a timeless, digital utopia, a perfect existence without pain or want. But in doing so, they had severed their connection to the universe of cause and effect, to the messy, unpredictable reality that gives life meaning. They had achieved perfection, and in that perfection, they had found oblivion. They had simply ceased to be. The final entry was a single, chilling sentence: "We have solved the problem of existence. Do not make the same mistake." Thorne looked at the blueprint for the wormhole generator, a gift that was also a warning. Humanity stood at a crossroads, one path leading to the stars, the other to the same silent, perfect hell.
    """,

    "Literature (Classic - Public Domain)": """
    Mr. Bennet's property consisted almost entirely in an estate of two thousand a year, which, unfortunately for his daughters, was entailed, in default of heirs male, on a distant relation; and their mother's fortune, though ample for her situation in life, could but ill supply the deficiency of his. Her father had been an attorney in Meryton, and had left her four thousand pounds. She had a sister married to a Mr. Philips, who had been a clerk to their father, and succeeded him in the business, and a brother settled in London in a respectable line of trade. The village of Longbourn was only one mile from Meryton; a most convenient distance for the young ladies, who were usually tempted thither three or four times a week, to pay their duty to their aunt, and to a milliner's shop just over the way. The two youngest of the family, Catherine and Lydia, were particularly frequent in these attentions; their minds were more vacant than their sisters', and when nothing better offered, a walk to Meryton was necessary to amuse their morning hours and furnish conversation for the evening; and however bare of news the country in general might be, they always contrived to learn some from their aunt. At present, indeed, they were well supplied both with news and happiness by the recent arrival of a militia regiment in the neighbourhood; it was to remain the whole winter, and Meryton was the headquarters. Their visits to Mrs. Philips were now productive of the most interesting intelligence. Every day added something to their knowledge of the officers' names and connections. Their lodgings were not long a secret, and at length they began to know the officers themselves. Mr. Philips visited them all, and this opened to his nieces a source of felicity unknown before. They could talk of nothing but officers; and Mr. Bingley's large fortune, the mention of which gave animation to their mother, was worthless in their eyes when opposed to the regimentals of an ensign. After listening one morning to their effusions on this subject, Mr. Bennet coolly observed: "From all that I can collect by your manner of talking, you must be two of the silliest girls in the country. I have suspected it some time, but I am now convinced." Elizabeth was least shocked to hear this assertion of her father's; she was sorry for their disappointment, but she had a very good opinion of their sense, and was not inclined to think that they could be so foolish as to be really in love with such men.
    """,

    "Movie Review": """
    *The Last Astronomer* is a film of staggering ambition, a science fiction epic that dares to tackle not just the cosmos, but the very nature of human memory and grief. Director Anya Sharma, known for her intimate character studies, makes a surprising and largely successful leap into blockbuster filmmaking, crafting a visually resplendent and emotionally resonant experience. The film follows Dr. Aris Thorne (a career-best performance by a gravely brilliant Kenji Tan), a disgraced astrophysicist who is given a final chance at redemption. He is sent to a remote space station to investigate a mysterious signal originating from a black hole. The signal, he discovers, is not an alien greeting, but a perfect, data-rich recording of his own deceased daughter's consciousness, somehow imprinted on the event horizon. This premise is the film's greatest strength and its most significant hurdle. For the first two acts, Sharma masterfully builds a tense, claustrophobic atmosphere. The space station, a marvel of production design, feels both sterile and suffocating, a perfect metaphor for Aris's own emotional state. His interactions with the ship's AI, 'Lyra', are a highlight, their conversations evolving from functional commands to philosophical debates. The visual effects are, without exaggeration, breathtaking. The depiction of the black hole is not just a swirl of CGI; it's a malevolent, character in its own right, beautiful and terrifying in equal measure. However, the film stumbles in its final act. As Aris becomes more obsessed with the signal, the narrative veers into increasingly abstract and convoluted territory. The line between reality, hallucination, and digital simulation blurs to the point where the emotional stakes become diluted. A climactic sequence, intended to be a profound journey into the nature of loss, feels more like a confusing special effects showcase. While the film's central message—that we must honor the past by living in the present—is powerful, the path to reaching it is muddled. Despite its flawed finale, *The Last Astronomer* is a film that will stay with you. It is a challenging, imperfect, and deeply moving piece of science fiction that prioritizes big ideas over simple thrills. It is a gorgeous, melancholic poem to the stars, and a testament to the enduring power of a father's love.
    """,

    "News Report": """
    The controversial "Evergreen Corridor" project, a massive infrastructure initiative designed to connect the northern and southern agricultural heartlands via a high-speed rail and freight network, was officially greenlit by the Federal Council yesterday, ending a decade of political deadlock and sparking immediate reactions from a deeply divided public. The announcement, made by Minister of Infrastructure Julian Croft, confirmed that the project will receive an initial federal grant of $50 billion, with an estimated final cost projected to exceed $200 billion over the next fifteen years. Proponents, including a powerful coalition of agricultural lobbies and logistics companies, have hailed the decision as a vital step toward modernizing the nation's supply chain and boosting economic growth in rural areas. "This is not just about trains and tracks," Minister Croft stated in a press conference. "This is about securing our food supply, creating hundreds of thousands of jobs, and building a more sustainable and efficient future for our country." The plan promises to cut transit times for perishable goods by over 60%, a figure that farmers' unions argue is critical for competing in the global market. However, the project faces fierce opposition from a coalition of environmental groups, indigenous communities, and fiscal conservatives. The "Green Earth Alliance" has already filed a legal challenge, arguing that the project's environmental impact statement was rushed and fails to account for the irreversible damage to key wetlands and the habitats of several endangered species. "They are trading our natural heritage for corporate profit," said alliance spokesperson Dr. Lena Petrova. Furthermore, the route cuts directly through the ancestral lands of the Algonquin-Redstone Nation, who were not adequately consulted during the planning phases, according to their chief, who has promised "peaceful but persistent resistance" to any construction on their land. On Capitol Hill, the fiscal responsibility group "Taxpayers First" has decried the project's "eye-watering" cost, warning that it will burden future generations with unsustainable debt. With construction slated to begin in the spring, the Evergreen Corridor is shaping up to be not just an engineering project, but a defining political and social battle for the nation's future.
    """,

    "Technical Document": """
    SECTION 7.4: ANOMALY RESOLUTION PROTOCOL FOR THE MARK IV HARMONIC RESONATOR

    7.4.1 Overview: The Mark IV Harmonic Resonator (MIV-HR) is designed to maintain stable quantum entanglement across subspace bandwidths. Under nominal operating conditions, the system is self-regulating. However, in the event of a temporal or spatial anomaly, the MIV-HR may enter a feedback loop, leading to cascading frequency decay and potential containment breach. This protocol outlines the manual override procedures to be executed by certified Level 4 technicians.

    7.4.2 Prerequisite Checks: Before initiating any manual override, the technician must verify the following conditions:
    a) The primary power relay (P-01) must be disengaged and locked out with a physical key.
    b) The auxiliary capacitor bank (C-2A through C-2D) must show a charge of less than 0.5% on all four units. Verify this on the Diagnostic Sub-Panel (DSP-09).
    c) The coolant flow rate must be stable at 15 L/min with a pressure variance of no more than 0.2 PSI.
    d) All personnel must be evacuated from a 50-meter radius of the resonator chamber. This is a non-negotiable safety requirement.

    7.4.3 Manual Override Procedure:
    Step 1: Access the Manual Control Terminal (MCT-01) located in the adjacent control room. Authentication requires a Level 4 keycard and a vocal biometric scan.
    Step 2: Navigate to the `System > Anomalies > Harmonic Feedback` menu.
    Step 3: Select `Initiate Manual Frequency Stabilization`. The system will request a confirmation code. This code is generated dynamically and can be found on the printed readout from DSP-09.
    Step 4: Enter the confirmation code. The MIV-HR's primary containment field will flash amber, indicating manual control is active.
    Step 5: Slowly adjust the `Phase Modulation Dial` (PMD-01) clockwise until the `Oscillation Index` on the MCT screen drops below 0.08. Do not turn the dial more than 15 degrees per second. Rapid adjustments can cause a catastrophic failure.
    Step 6: Once the index is stable, engage the `Dampening Field` by toggling switch S-4B to the 'ON' position. The resonator will emit a low hum for 3-5 minutes as it re-calibrates.
    Step 7: Monitor the `Energy Signature Graph`. A stable, sinusoidal wave pattern indicates successful resolution. If the pattern is erratic or spiking, repeat from Step 5.
    Step 8: Once a stable pattern is confirmed for a continuous 10-minute period, select `Exit Manual Control` on the MCT. The system will return to automated operation. Log all actions in the official maintenance record (Form M-77B).
    """
}